# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7d69236c-bae0-4171-b06f-25f3b367510b";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/920B-CD82";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/7d69236c-bae0-4171-b06f-25f3b367510b";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/7d69236c-bae0-4171-b06f-25f3b367510b";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/data/media" =
    { device = "data/media/backup";
      fsType = "zfs";
      options = [ "noauto" ];
    };

  fileSystems."/data/music" =
    { device = "data/media/music";
      fsType = "zfs";
      options = [ "noauto" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4fc7b43b-d553-4ddb-bb41-b0a25d308f83"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
