# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" "it87" ];
  boot.extraModulePackages = [ ];

  # Main SSD partition with various BTRFS subvolumes
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/730d4516-29c2-4ee2-a6a7-063dbba40a3b";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/730d4516-29c2-4ee2-a6a7-063dbba40a3b";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/730d4516-29c2-4ee2-a6a7-063dbba40a3b";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  # EFI Boot Partition (ESP)
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8CB9-8FD9";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4fc7b43b-d553-4ddb-bb41-b0a25d308f83"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 4;
}
