# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  # Decrypt system and mirror partition
  boot.initrd.luks.devices."system".device = "/dev/disk/by-uuid/4d502e8b-64aa-4497-b6ab-b028d512241c";
  boot.initrd.luks.devices."system-mirror".device = "/dev/disk/by-uuid/06c62ab3-01a2-4a73-9b39-8dc2021ca1c8";

  # UEFI boot partition and mirror
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3495-93CF";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/boot-mirror" =
    { device = "/dev/disk/by-uuid/33FE-EAB3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Subvolumes on main btrfs mirror
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/20f93c80-4b4b-423c-bae0-b63c8cf63cd3";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

   fileSystems."/home" =
    { device = "/dev/disk/by-uuid/20f93c80-4b4b-423c-bae0-b63c8cf63cd3";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/20f93c80-4b4b-423c-bae0-b63c8cf63cd3";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  # Additional subvolumes in home folder
  fileSystems."/home/florian/.local/share/Steam" =
    { device = "/dev/disk/by-uuid/20f93c80-4b4b-423c-bae0-b63c8cf63cd3";
      fsType = "btrfs";
      options = [ "subvol=@steam" "compress=zstd" "noatime" ];
    };

  # Btrfs root mount point used by btrbk
  fileSystems."/tardis/system" = {
    device = "/dev/disk/by-uuid/20f93c80-4b4b-423c-bae0-b63c8cf63cd3";
    fsType = "btrfs";
    options = [ "compress=zstd" "noatime" ];
  };

  # Regurlary scrub btrfs mirror
  services.btrfs.autoScrub = {
    enable = true;
    fileSystems = [ "/tardis/system" ];
  };

  # Only use the SSD with DRAM for (encrypted) swap
  swapDevices = [{ 
    device = "/dev/disk/by-partuuid/223c535d-79d2-47fa-84dd-fa683fcacf14";
    randomEncryption = {
      enable = true;
      allowDiscards = true;
    };
  }];
}
