# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/01b3540e-1ad2-4ac9-abe7-902e1f4b924d";
  
  fileSystems."/" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/home/florian/Backup" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=@backup" ];
    };

  fileSystems."/home/florian/Wine" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=@wine" ];
    };

  fileSystems."/var/lib/libvirt" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=@virt" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8BFF-3A0D";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2f76a2ec-4c66-419d-ac70-a06f96c67884"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
