# Generated by ‘nixos-generate-config’ and then modified.
{ ... }:

{
  # SYSTEM: Btrfs mirror with subvolume for root, home and nix store
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/931bb88a-13a4-406c-9478-ebfb8e8ed2d8";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/931bb88a-13a4-406c-9478-ebfb8e8ed2d8";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/931bb88a-13a4-406c-9478-ebfb8e8ed2d8";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
      "noatime"
    ];
  };

  # SYSTEM: Additional subvolumes mounted into home to reduce snapshot sizes
  fileSystems."/home/florian/.local/share/Steam" = {
    device = "/dev/disk/by-uuid/931bb88a-13a4-406c-9478-ebfb8e8ed2d8";
    fsType = "btrfs";
    options = [
      "subvol=@steam"
      "compress=zstd"
      "noatime"
    ];
  };

  # DATA: Additional subvolumes on second drive mounted into home
  fileSystems."/home/florian/Backups" = {
    device = "/dev/disk/by-uuid/160cf71a-2e13-4dbf-98fb-db9936884885";
    fsType = "btrfs";
    options = [
      "subvol=@backups"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/home/florian/Cloud" = {
    device = "/dev/disk/by-uuid/160cf71a-2e13-4dbf-98fb-db9936884885";
    fsType = "btrfs";
    options = [
      "subvol=@cloud"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/home/florian/Music" = {
    device = "/dev/disk/by-uuid/160cf71a-2e13-4dbf-98fb-db9936884885";
    fsType = "btrfs";
    options = [
      "subvol=@music"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/home/florian/ROMs" = {
    device = "/dev/disk/by-uuid/160cf71a-2e13-4dbf-98fb-db9936884885";
    fsType = "btrfs";
    options = [
      "subvol=@roms"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/home/florian/Videos" = {
    device = "/dev/disk/by-uuid/160cf71a-2e13-4dbf-98fb-db9936884885";
    fsType = "btrfs";
    options = [
      "subvol=@videos"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/home/florian/.local/share/MoreSteam" = {
    device = "/dev/disk/by-uuid/160cf71a-2e13-4dbf-98fb-db9936884885";
    fsType = "btrfs";
    options = [
      "subvol=@steam"
      "compress=zstd"
      "noatime"
    ];
  };

  # SERVICES: Additional subvolumes for services
  fileSystems."/var/lib/libvirt" = {
    device = "/dev/disk/by-uuid/160cf71a-2e13-4dbf-98fb-db9936884885";
    fsType = "btrfs";
    options = [
      "subvol=@libvirt"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/var/lib/private/ollama" = {
    device = "/dev/disk/by-uuid/931bb88a-13a4-406c-9478-ebfb8e8ed2d8";
    fsType = "btrfs";
    options = [
      "subvol=@ollama"
      "compress=zstd"
      "noatime"
    ];
  };

  # Mirrored UEFI boot partitions
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/18C3-DE52";
    fsType = "vfat";
  };

  fileSystems."/boot-mirror" = {
    device = "/dev/disk/by-uuid/4F0A-FB18";
    fsType = "vfat";
  };

  # Regurlary scrub btrfs mirrors
  services.btrfs.autoScrub = {
    enable = true;
    fileSystems = [
      "/tardis/system"
      "/tardis/data"
    ];
  };

  # Enable daily home snapshots
  services.tardis = {
    enable = true;
    device = "/dev/disk/by-uuid/931bb88a-13a4-406c-9478-ebfb8e8ed2d8";
  };

  # Extra mount point for btrbk
  fileSystems."/tardis/data" = {
    device = "/dev/disk/by-uuid/160cf71a-2e13-4dbf-98fb-db9936884885";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
    ];
  };

  # One swap partition per drive
  swapDevices = [
    { device = "/dev/disk/by-uuid/adbaba96-3f04-45d3-ad7a-82ab8af0f863"; }
    { device = "/dev/disk/by-uuid/628cf232-00fb-45a6-9e3f-4556ba4e7524"; }
  ];
}
