# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/20f93c80-4b4b-423c-bae0-b63c8cf63cd3";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  boot.initrd.luks.devices."system".device = "/dev/disk/by-uuid/4d502e8b-64aa-4497-b6ab-b028d512241c";
  boot.initrd.luks.devices."system-mirror".device = "/dev/disk/by-uuid/06c62ab3-01a2-4a73-9b39-8dc2021ca1c8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3495-93CF";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/boot-mirror" =
    { device = "/dev/disk/by-uuid/33FE-EAB3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

   fileSystems."/home" =
    { device = "/dev/disk/by-uuid/20f93c80-4b4b-423c-bae0-b63c8cf63cd3";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/20f93c80-4b4b-423c-bae0-b63c8cf63cd3";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d680f4db-6237-401a-8153-2be09ee8e354"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
